Repository Team1559/2025-Reefscape, pull requests merged in 2025-02, with the labels that each got.

#8 Implement Elevator
  src/main/java/frc/lib/BaseIo.java
  src/main/java/frc/lib/subsystems/elevator/Elevator.java
  src/main/java/frc/lib/subsystems/elevator/ElevatorIo.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/subsystems/Elevator2025.java
  src/main/java/frc/robot/subsystems/ElevatorIo2025.java
Labels: feature

#9 Update vendor dependencies to latest version
  vendordeps/AdvantageKit.json
  vendordeps/PathplannerLib.json
  vendordeps/Phoenix6-frc2025-latest.json
  vendordeps/REVLib.json
  vendordeps/photonlib.json
Labels: dependencies

#10 Updating swerve code
  src/main/java/frc/lib/components/gyro/GyroIo.java
  src/main/java/frc/lib/components/gyro/Pigeon2Io.java
  src/main/java/frc/lib/subsystems/LoggableIo.java
  src/main/java/frc/lib/subsystems/LoggableSubsystem.java
  src/main/java/frc/lib/subsystems/elevator/Elevator.java
  src/main/java/frc/lib/subsystems/elevator/ElevatorIo.java
  src/main/java/frc/lib/subsystems/swerve/SdsSwerveModuleIo.java
  src/main/java/frc/lib/subsystems/swerve/SwerveDrive.java
  src/main/java/frc/lib/subsystems/swerve/SwerveModuleIo.java
  src/main/java/frc/lib/subsystems/vision/Vision.java
  src/main/java/frc/lib/subsystems/vision/VisionCameraIo.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
Labels: cleanup, feature

#12 Moves mass and moment of inertia to SwerveDrive2025 from robot
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/subsystems/SwerveDrive2025.java
Labels: cleanup

#11 Elevator tested and functional
  .vscode/settings.json
  src/main/java/frc/lib/commands/ElevatorHeightCommand.java
  src/main/java/frc/lib/subsystems/elevator/Elevator.java
  src/main/java/frc/lib/subsystems/elevator/ElevatorIo.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/commands/ElevatorHeightCommand2025.java
  src/main/java/frc/robot/subsystems/Elevator2025.java
  src/main/java/frc/robot/subsystems/ElevatorIo2025.java
  visiondata/frontleftcalibration8-2-25.cal
  visiondata/frontleftpipeline.vpr
  visiondata/frontleftpipeline8-2-25.vpr
  visiondata/frontrightcalibration2-8-25.cal
  visiondata/frontrightpipeline.vpr
  visiondata/frontrightpipeline8-2-25.vpr
Labels: feature, testing

#13 Intake code first version (untested)
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/commands/AlgaeIntakeAngleCommand.java
  src/main/java/frc/robot/commands/CoralIntakeAngleCommand.java
  src/main/java/frc/robot/commands/IntakeAngleCommand.java
  src/main/java/frc/robot/subsystems/intake/AlgaeIntake.java
  src/main/java/frc/robot/subsystems/intake/AlgaeIntakeIo.java
  src/main/java/frc/robot/subsystems/intake/CoralIntake.java
  src/main/java/frc/robot/subsystems/intake/CoralIntakeIo.java
  src/main/java/frc/robot/subsystems/intake/Intake.java
  src/main/java/frc/robot/subsystems/intake/IntakeIo.java
Labels: feature, testing

#14 Fixed compile errors with imports
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/subsystems/intake/Intake.java
  src/main/java/frc/robot/subsystems/intake/IntakeIo.java
Labels: bug

#16 Vision fixes and standard deviations
  src/main/java/frc/lib/subsystems/swerve/SwerveDrive.java
  src/main/java/frc/lib/subsystems/vision/LimelightCameraIo.java
  src/main/java/frc/lib/subsystems/vision/Vision.java
  src/main/java/frc/lib/subsystems/vision/VisionCameraIo.java
  src/main/java/frc/robot/Robot.java
Labels: cleanup, feature

#15 Commands for autonomous (untested)
  src/main/deploy/pathplanner/autos/Inside_2_CoralL2.auto
  src/main/deploy/pathplanner/autos/Inside_4_CoralL2.auto
  src/main/deploy/pathplanner/autos/Inside_4_CoralL4.auto
  src/main/deploy/pathplanner/autos/Inside_Drive.auto
  src/main/deploy/pathplanner/autos/Low-2-To-Processor.auto
  src/main/deploy/pathplanner/autos/Low-3-To-Processor.auto
  src/main/deploy/pathplanner/autos/Low-6-To-Processor.auto
  src/main/deploy/pathplanner/autos/MId-2-To-Processor.auto
  src/main/deploy/pathplanner/autos/Mid-3-To-Processor.auto
  src/main/deploy/pathplanner/autos/Mid-4-To-Processor.auto
  src/main/deploy/pathplanner/autos/Mid_12_CoralL2.auto
  src/main/deploy/pathplanner/autos/Mid_1_CoralL2.auto
  src/main/deploy/pathplanner/autos/Mid_Drive.auto
  src/main/deploy/pathplanner/autos/Outside_10_CoralL2.auto
  src/main/deploy/pathplanner/autos/Outside_12_CoralL4.auto
  src/main/deploy/pathplanner/autos/Outside_Drive.auto
  src/main/deploy/pathplanner/autos/Square.auto
  src/main/deploy/pathplanner/autos/Top-2-To-Processor.auto
  src/main/deploy/pathplanner/autos/Top-3-To-Processor.auto
  src/main/deploy/pathplanner/autos/low-4-To-Processor .auto
  src/main/deploy/pathplanner/autos/mid-1-To-Processor.auto
  src/main/deploy/pathplanner/paths/10_Processor.path
  src/main/deploy/pathplanner/paths/3-Processor.path
  src/main/deploy/pathplanner/paths/4_Processor.path
  src/main/deploy/pathplanner/paths/6-Processor.path
  src/main/deploy/pathplanner/paths/Inside_2.path
  src/main/deploy/pathplanner/paths/Inside_4.path
  src/main/deploy/pathplanner/paths/Inside_Drive.path
  src/main/deploy/pathplanner/paths/Inside_to1.path
  src/main/deploy/pathplanner/paths/Inside_to5.path
  src/main/deploy/pathplanner/paths/Mid-7.path
  src/main/deploy/pathplanner/paths/Mid-Foward.path
  src/main/deploy/pathplanner/paths/Mid_1.path
  src/main/deploy/pathplanner/paths/Mid_12.path
  src/main/deploy/pathplanner/paths/Mid_2.path
  src/main/deploy/pathplanner/paths/Mid_3.path
  src/main/deploy/pathplanner/paths/Mid_5.path
  src/main/deploy/pathplanner/paths/Mid_Drive.path
  src/main/deploy/pathplanner/paths/Outside-3.path
  src/main/deploy/pathplanner/paths/Outside-5.path
  src/main/deploy/pathplanner/paths/Outside-8.path
  src/main/deploy/pathplanner/paths/Outside_10.path
  src/main/deploy/pathplanner/paths/Outside_11.path
  src/main/deploy/pathplanner/paths/Outside_12.path
  src/main/deploy/pathplanner/paths/Outside_Drive.path
  src/main/deploy/pathplanner/paths/Outside_Forward.path
  src/main/deploy/pathplanner/paths/Square_1 .path
  src/main/deploy/pathplanner/paths/Square_2.path
  src/main/deploy/pathplanner/paths/Square_3.path
  src/main/deploy/pathplanner/paths/Square_4.path
  src/main/deploy/pathplanner/paths/inside_Forward.path
  src/main/deploy/pathplanner/paths/inside_to11.path
  src/main/deploy/pathplanner/settings.json
  src/main/java/frc/robot/Robot.java
Labels: feature

#17 Create Github Actions CI build
  .github/workflows/wpilib-build.yml
Labels: testing
